alias: HELIOS Optimizer Automation Task
description: >-
  A Home Assistant Automatioin Task that Configures and Starts the Helios
  Optimizer Service

  This Task runs (every quarter of an hour and at HA startup) the Helios
  Optimizer Service  which uses the SciPy (LP/MILP) HiGHS Solver to Optimize the
  Energy Plan.  Inputs are the Import and Export Price arrays, the House Energy
  Usage and the Solar Forecast arrays.

  Every quarter of an hour a new Optimalized Energy Plan is calculated for the
  House.

  Set the start step at 0 to start the optimalization at the current hour. Use a
  start step of 1 or higher to start at a fixed step (to get a more predictable
  result for simulation runs).

  The results (payload) are visible in the trace of this automation and are also
  stored in the HA Entity: input_number.helios_optimizer_energy_plan. A HA
  Notification will be sent when the optimization is Infeasible or Fails (with
  an Error or an Exception). The automation also contains a notification for
  successful optimizations but it is advised to disable these notification
  during normal operation.
triggers:
  - trigger: time_pattern
    alias: Triggers the Automation at the Quarter of an Hour
    id: HA-Hourly
    minutes: /15
  - trigger: homeassistant
    alias: Triggers the Automation at Startup of Home Assistant
    event: start
    id: HA-Start
conditions: []
actions:
  - alias: For a HA Restart - Delay 10s to allow PyScript to load and start
    if:
      - condition: trigger
        alias: Home Assistant Restart?
        id:
          - HA-Start
    then:
      - alias: Delay the automation for 10s to allow PyScript to load and start
        delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
  - alias: Default Optimizer Parameters (for Test Runs)
    variables:
      default_version: 99.99.99
      default_steps: 24
      default_step_size: 60
      default_start_step: 0
      default_input_size: 60
      default_price_factor: 1
      default_solar_mode: all
      default_battery_enabled: true
      default_maximum_kwh: 10
      default_soc_start_pct: 95
      default_soc_target_pct: 45
      default_soc_min_pct: 10
      default_soc_max_pct: 80
      default_max_grid_import_kw: 9
      default_max_grid_export_kw: 9
      default_charge_limit_kw: 3
      default_discharge_limit_kw: 3
      default_charge_eff: 0.75
      default_discharge_eff: 0.95
      default_charge_cost: 0
      default_discharge_cost: 0.01
      default_house_daily_usage: 12
      default_house_daily_distr_str: '[1, 1 ,1, 1, 1, 1, 1, 3, 3, 2, 2, 2, 3, 2, 2, 2, 2, 3,12,12, 8, 8,3, 1]'
      default_import_prices_str: >-
        [0.25,0.2,0.18,0.15,0.14,0.18,0.28,0.35,0.3,0.22,0.15,0.1,0.05,0.08,0.12,0.2,0.32,0.4,0.35,0.28,0.25,0.22,0.2,0.18]
      default_export_prices_str: >-
        [0.01,0.05,0.03,0.01,0,0.02,0.1,0.15,0.12,0.05,0,-0.02,-0.05,-0.02,0.01,0.05,0.12,0.18,0.15,0.1,0.08,0.06,0.05,0.04]
      default_house_energy_forecast_str: >-
        [0.4,0.3,0.3,0.4,0.5,0.8,1.2,1,0.8,0.6,0.5,0.5,0.4,0.4,0.5,0.6,0.9,1.5,1.2,1,0.8,0.6,0.5,0.4]
      default_solar_energy_forecast_str: '[0,0,0,0,0,0.1,0.8,2,3.5,4.8,5.5,5.8,5.6,4.9,3.8,2.2,1,0.2,0,0,0,0,0,0]'
      default_write_files: true
      default_output_folder: null
  - alias: HBC and Helios Template (from HBC) Sensor Names
    variables:
      helios_sensor_version: input_text.helios_optimizer_version
      helios_sensor_steps: input_number.helios_optimizer_steps
      helios_sensor_step_size: input_select.helios_optimizer_step_size
      helios_sensor_solar_mode: input_select.helios_optimizer_solar_mode
      helios_sensor_battery_enabled: input_boolean.helios_optimizer_battery_enabled
      helios_sensor_start_step: input_number.helios_optimizer_start_step
      helios_sensor_house_daily_usage: input_number.helios_optimizer_house_daily_usage
      helios_sensor_house_daily_distr: input_text.helios_optimizer_house_daily_distr
      helios_sensor_soc_target_pct: input_number.helios_optimizer_soc_target_pct
      helios_sensor_soc_min_pct: input_number.helios_optimizer_soc_min_pct
      helios_sensor_soc_max_pct: input_number.helios_optimizer_soc_max_pct
      helios_sensor_max_grid_import: input_number.helios_optimizer_max_grid_import
      helios_sensor_max_grid_export: input_number.helios_optimizer_max_grid_export
      helios_sensor_charge_limit: input_number.helios_optimizer_charge_limit
      helios_sensor_discharge_limit: input_number.helios_optimizer_discharge_limit
      helios_sensor_charge_eff: input_number.helios_optimizer_charge_efficiency
      helios_sensor_discharge_eff: input_number.helios_optimizer_discharge_efficiency
      hbc_sensor_battery_count: input_number.house_battery_count
      hbc_sensor_battery_maximum_energy: input_number.house_battery_total_max_available_energy
      hbc_sensor_battery_remaining_energy: input_number.house_battery_total_available_energy
      hbc_sensor_soc_min: input_number.house_battery_strategy_sell_target_soc
      hbc_sensor_soc_max: input_number.house_battery_strategy_charge_target_soc
      hbc_sensor_prices: sensor.hbc_energy_prices_data
      hbc_prices_attr_marks: marks
      hbc_prices_attr_prices: prices
      hbc_prices_attr_start: start
      hbc_prices_attr_dp_ph: datapoints_per_hour
      hbc_prices_all_attr: null
      hbc_price_factor: 0.01
      helios_template_hbc_maximum_energy: sensor.helios_template_hbc_maximum_energy
      helios_template_hbc_remaining_energy: sensor.helios_template_hbc_remaining_energy
      helios_template_hbc_total_soc: sensor.helios_template_hbc_total_soc
      helios_template_hbc_max_charge_power: sensor.helios_template_hbc_max_charge_power
      helios_template_hbc_max_discharge_power: sensor.helios_template_hbc_max_discharge_power
      helios_template_solar_forecast: sensor.helios_optimizer_forecast_solar_hours
      helios_solar_result: result
      helios_solar_hours: hours_kwh
  - alias: Retrieve the Helios Optimizer Parameters (from the UI)
    variables:
      optimization_result:
        success: false
        solver_status: Helios Optimizer has not (yet) executed
      trigger_id: '{{ trigger.id | default(''No-Trigger-id'') }}'
      helios_version: '{{ states(helios_sensor_version) | default(default_version, true) }}'
      helios_steps: >-
        {{ states(helios_sensor_steps) | default(default_steps, true) |
        int(default_steps) }}
      helios_step_size: >-
        {{ states(helios_sensor_step_size) | default(default_step_size, true) |
        int(default_step_size) }}
      helios_start_step: >-
        {{ states(helios_sensor_start_step) | default(default_start_step, true)
        | int(default_start_step) }}
      helios_house_daily_usage: >-
        {{ states(helios_sensor_house_daily_usage) |
        default(default_house_daily_usage, true) |
        int(default_house_daily_usage) }}
      helios_house_daily_distr: >-
        {{ states(helios_sensor_house_daily_distr) |
        default(default_house_daily_distr_str, true) }}
      helios_solar_mode: >-
        {{ states(helios_sensor_solar_mode) | default(default_solar_mode, true)
        }}
      helios_solar_enabled: '{{ helios_solar_mode in [''all'',''modulating'',''binary''] }}'
      helios_battery_enabled: >-
        {{ states(helios_sensor_battery_enabled) |
        default(default_battery_enabled, true) | bool(default_battery_enabled)
        }}
      helios_soc_target_pct: >-
        {{ states(helios_sensor_soc_target_pct) |
        default(default_soc_target_pct, true) | float(default_soc_target_pct) }}
      helios_soc_min_pct: >-
        {{ states(helios_sensor_soc_min_pct) | default(default_soc_min_pct,
        true) | float(default_soc_min_pct) }}
      helios_soc_max_pct: >-
        {{ states(helios_sensor_soc_max_pct) | default(default_soc_min_pct,
        true) | float(default_soc_max_pct) }}
      helios_max_grid_import_kw: >-
        {{ states(helios_sensor_max_grid_import) |
        default(default_max_grid_import_kw, true) |
        float(default_max_grid_import_kw) }}
      helios_max_grid_export_kw: >-
        {{ states(helios_sensor_max_grid_export) |
        default(default_max_grid_export_kw, true) |
        float(default_max_grid_export_kw) }}
      helios_charge_limit_kw: >-
        {{ states(helios_sensor_charge_limit) | default(default_charge_limit_kw,
        true) | float(default_charge_limit_kw) }}
      helios_discharge_limit_kw: >-
        {{ states(helios_sensor_discharge_limit) |
        default(default_discharge_limit_kw, true) |
        float(default_discharge_limit_kw) }}
      helios_charge_eff: >-
        {{ states(helios_sensor_charge_eff) | default(default_charge_eff, true)
        | float(default_charge_eff) }}
      helios_discharge_eff: >-
        {{ states(helios_sensor_discharge_eff) | default(default_discharge_eff,
        true) | float(default_discharge_eff) }}
      helios_solar_forecast_result: >-
        {{ state_attr(helios_template_solar_forecast, helios_solar_result) |
        default({}, true) }}
      helios_solar_energy_forecast_rest: '{{ helios_solar_forecast_result.get(helios_solar_hours, []) }}'
      helios_solar_energy_forecast_default: '{{ default_solar_energy_forecast_str | from_json }}'
      helios_house_energie_forecast_default: '{{ default_house_energy_forecast_str | from_json }}'
      helios_house_energy_forecast_null: null
  - alias: Retrieve the HBC Optimizer Parameters
    variables:
      hbc_battery_count: '{{ states(hbc_sensor_battery_count) | default(0, true) }}'
      hbc_maximum_kwh: '{{ states(hbc_sensor_battery_maximum_energy) | default(0, true) }}'
      hbc_remaining_kwh: '{{ states(hbc_sensor_battery_remaining_energy) | default(0, true) }}'
      hbc_soc_start_pct: >-
        {{ ((100 * hbc_remaining_kwh / hbc_maximum_kwh) if (hbc_maximum_kwh !=
        0) else 0) | round(1) }}
      hbc_soc_min_pct: >-
        {{ states(hbc_sensor_soc_min) | default(default_soc_min, true) |
        float(default_soc_min) }}
      hbc_soc_max_pct: >-
        {{ states(hbc_sensor_soc_max) | default(default_soc_max, true) |
        float(default_soc_max) }}
      hbc_prices_all: '{{ state_attr(hbc_sensor_prices, null) | default([], true) }}'
      hbc_marks: >-
        {{ state_attr(hbc_sensor_prices, hbc_prices_attr_marks) | default([],
        true) }}
      hbc_prices: >-
        {{ state_attr(hbc_sensor_prices, hbc_prices_attr_prices) | default([],
        true) }}
      hbc_prices_null: null
      hbc_prices_start: >-
        {{ state_attr(hbc_sensor_prices, hbc_prices_attr_start) | default(none,
        true) }}
      hbc_prices_dp_ph: >-
        {{ state_attr(hbc_sensor_prices, hbc_prices_attr_dp_ph) | default(1,
        true) | int(1) }}
      hbc_prices_length: '{{ hbc_prices | length }}'
      hbc_prices_interval: '{{ (60 / hbc_prices_dp_ph) | int(0) }}'
      hbc_price_data: '{{ dict(states[hbc_sensor_prices].attributes) }}'
  - alias: >-
      Retrieve the Helios Optimizer Parameters based (via Templates) on HBC
      Sensors. It turned out that HBC sensors are not always available or are
      already corrected for min/max soc values.
    variables:
      hbc_helios_maximum_kwh: '{{ states(helios_template_hbc_maximum_energy) | default(none, true) }}'
      hbc_helios_remaining_kwh: '{{ states(helios_template_hbc_remaining_energy) | default(none, true) }}'
      hbc_helios_soc_start_pct: '{{ states(helios_template_hbc_total_soc) | default(none, true) }}'
      hbc_helios_max_charge_power_kw: >-
        {{ (states(helios_template_hbc_max_charge_power) |
        default(helios_charge_limit_kw, true) | int(helios_charge_limit_kw) /
        1000) | round(1) }}      
      hbc_helios_max_discharge_power_kw: >-
        {{ (states(helios_template_hbc_max_discharge_power) |
        default(helios_discharge_limit_kw, true) |
        int(helios_discharge_limit_kw) / 1000) | round(1) }}
  - action: pyscript.helios_optimizer_service
    alias: Start the PyScript Helios Optimizer Service
    continue_on_error: true
    response_variable: optimization_payload
    data:
      steps: '{{ helios_steps }}'
      step_size: '{{ helios_step_size }}'
      start_step: '{{ helios_start_step }}'
      price_size: '{{ hbc_prices_interval }}'
      house_size: '{{ default_input_size }}'
      solar_size: '{{ default_input_size }}'
      price_factor: '{{ hbc_price_factor }}'
      max_grid_import_kw: '{{ helios_max_grid_import_kw }}'
      max_grid_export_kw: '{{ helios_max_grid_export_kw }}'
      battery:
        enabled: '{{ helios_battery_enabled }}'
        capacity_kwh: '{{ hbc_helios_maximum_kwh }}'
        soc_start_pct: '{{ hbc_helios_soc_start_pct }}'
        soc_target_pct: '{{ helios_soc_target_pct }}'
        soc_min_pct: '{{ hbc_soc_min_pct }}'
        soc_max_pct: '{{ hbc_soc_max_pct }}'
        max_charge_power_kw: '{{ helios_charge_limit_kw }}'
        max_discharge_power_kw: '{{ helios_discharge_limit_kw }}'
        charge_efficiency: '{{ helios_charge_eff }}'
        discharge_efficiency: '{{ helios_discharge_eff }}'
        charge_cost: '{{ default_charge_cost }}'
        discharge_cost: '{{ default_discharge_cost }}'
      solar:
        enabled: '{{ helios_solar_enabled }}'
        mode: '{{ helios_solar_mode }}'
        energy_forecast: '{{ helios_solar_energy_forecast_rest }}'
      house_energy_forecast: '{{ helios_house_energy_forecast_null }}'
      house_daily_usage: '{{ helios_house_daily_usage }}'
      house_daily_distr: '{{ helios_house_daily_distr }}'
      import_prices: '{{ hbc_prices_null }}'
      export_prices: '{{ hbc_prices_null }}'
      provider_key: hbc_marks
      source_price_sensor: '{{ hbc_sensor_prices }}'
      source_price_data: '{{ hbc_prices_null }}'
      source_type: import
      original_provider: frank_energie
      insight: 9
      write_files: '{{ default_write_files }}'
      output_folder: '{{ default_output_folder }}'
    enabled: true
  - alias: >-
      Determine the results of the Helios Optimalization for the Battery (e.g.
      Strategy, Net Power (+/-) and Charge/Discharge Power (always +), etc)
    variables:
      optimization_success: >-
        {{ optimization_payload is defined and (optimization_payload.success |
        default(false, false)) == true }}
      optimization_result: >-
        {{ (optimization_payload.calc_result | default('RESULT Missing', false))
        if optimization_payload is defined else 'PAYLOAD Missing' }}
      optimization_message: >-
        {{ optimization_payload.solver_message | default('The Helios Solver
        MESSAGE is NOT available', true) if optimization_payload is defined else
        'The Helios Optimizer PAYLOAD IS NOT available!'}}
      optimization_total_fun_cost: >-
        {{ optimization_payload.total_fun_cost | default('FUN COST Missing',
        true) if optimization_payload is defined else 'PAYLOAD Missing'}}
      optimization_steps: >-
        {{ (optimization_payload.steps | default(-1, false)) if
        optimization_payload is defined else -2 }}
      optimization_current: >-
        {{ optimization_payload.get('current', none) if optimization_payload is
        defined else none }}
      optimization_battery_strategy: '{{ (optimization_current.battery_strategy | default(none, false)) }}'
      optimization_battery_net_power: '{{ (optimization_current.battery_net_power_w | default(none, false)) }}'
      optimization_battery_charge: '{{ (optimization_current.battery_charge_w | default(-1, false)) }}'
      optimization_battery_discharge: '{{ (optimization_current.battery_discharge_w | default(-1, false)) }}'
  - alias: Send a notification depending on the success of the Helios Optimizer
    if:
      - condition: template
        value_template: '{{ optimization_success }}'
        alias: Is the Optimalization successfull?
    then:
      - action: notify.persistent_notification
        data:
          title: HELIOS Optimizer Succeeded
          message: >-
            Helios Optimization succeeded: Total costs: €{{
            optimization_total_fun_cost }}
        alias: >-
          Send a notification when the Optimalization is successful (A new
          notification is added for each execution round; enable this step only
          for testing purposes)
        enabled: false
    else:
      - action: persistent_notification.create
        data:
          title: HELIOS Optimizer FAILED
          notification_id: helios_status_notification
          message: |
            Helios Optimalization FAILED with Result: '{{ optimization_result
            }}'.
            {{ optimization_message }}
        alias: >-
          Send a notification when the Helios Optimalisatie has failed (This
          notification replaces an earlier notification with the same
          notification id)
      - action: script.error
        data:
          message: >-
            The Helios Optimizer has failed! This step is designed to fail when
            executed with an 'Action script.error not found' error! See the
            notification in the previous step for details about the problems in
            the Helios Optimizer.
mode: single
